plugin: amazon.aws.aws_ec2
regions:
  - ap-south-1

filters:
  instance-state-name: running

keyed_groups:
  - key: tags.os
    prefix: tag_os

hostnames:
  - public-ip-address    # ✅ USE THIS — NOT public-dns-name

compose:
  ansible_host: public_ip_address   # ✅ CONNECT VIA PUBLIC IP
  ansible_ssh_user: "{{ 'ubuntu' if (tags.os | default('') | lower) == 'ubuntu' else 'ec2-user' }}"

ansible_ssh_common_args: >
  -o ProxyCommand="ssh -i {{ lookup('env','PEM_FILE') }} -W %h:%p -q ubuntu@{{ lookup('env','BASTION_IP') }}"

