plugin: amazon.aws.aws_ec2
regions:
  - ap-south-1

filters:
  instance-state-name: running

keyed_groups:
  - key: tags.os
    prefix: tag_os

compose:
  ansible_host: public_ip_address
  ansible_ssh_user: "{{ 'ubuntu' if 'ubuntu' in (tags.os | default('') | lower) else 'ec2-user' }}"

ansible_ssh_common_args: >
  -o ProxyCommand="ssh -i {{ lookup('env','PEM_FILE') }} -W %h:%p -q ubuntu@{{ lookup('env','BASTION_IP') }}"

